# Cấu hình huấn luyện cho luận văn Multimodal Negative Sampling
data:
  train_csv: "data/splits/train.csv"
  val_csv: "data/splits/val.csv"
  image_size: 256
  max_text_length: 128

model:
  embed_dim: 512
  image_encoder: "swinv2_base_window12to16_192to256"
  text_encoder: "emilyalsentzer/Bio_ClinicalBERT"
  temperature: 0.07

training:
  batch_size: 8              # <--- Nạp 8 ảnh/lượt
  gradient_accumulation_steps: 4 # <--- Chạy 4 lượt mới cập nhật (Tổng = 32)
  epochs: 1                  # <--- Vẫn để 1 để test xem nó chạy ổn không
  lr: 0.0001
  weight_decay: 0.01
  num_workers: 2
  max_steps_per_epoch: 500  
  log_every_n_steps: 10
  checkpoint_dir: "checkpoints/"


